version: '3'
services:
  node:
    restart: always    
    build:
      dockerfile: Dockerfile
    ports:
      - 80:5001
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:

